---
- name: system is up-to-date
  apt:
    update_cache=yes
    upgrade=full

- name: blocking packages are absent
  apt:
    pkg=python-pip
    state=absent
    purge=yes

- name: toolbox is well equipped
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - git
    - aptitude
    - build-essential
    - python-setuptools
    - python-dev
    - libffi-dev
    - libssl-dev
    - libzmq3-dev
    - libperl-dev
    - libzmq3
    - sudo

- name: pip is installed
  easy_install:
    name=pip

- name: mandatory python packages are installed
  pip:
    name="{{ item }}"
    state=latest
  with_items:
    - pip
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    - ansible
    - pyzmq
    - virtualenv

- name: ansible configuration directory is ready
  file:
    path='/etc/alfred'
    state='directory'
    owner='root'
    group='root'
    mode='0755'

- name: alfred is a system user
  user:
    name=alfred
    generate_ssh_key=yes
    ssh_key_bits=4096
    state=present

- name: default env variables are in place
  template:
    src='etc_default.j2'
    dest='/etc/default/alfred'
    owner='root'
    group='root'
    mode='0644'
  notify: restart alfred


- name: run directories are ready
  file:
    path="{{ item }}"
    state=directory
    owner=alfred
    group=alfred
    mode=2750
  with_items:
    - "/var/cache/alfred"
    - "/var/lib/alfred"
    - "/var/lib/alfred/playbooks"
    - "/var/lib/alfred/plugins"
    - "/var/lib/alfred/virtualenv"

- name: alfred action playbooks are present
  copy:
    src="install-plugin.yml"
    dest="/var/lib/alfred/playbooks/install-alfred-plugin.yml"
    owner=alfred
    group=alfred
    mode=0640

- name: alfred variables are present
  copy:
    src='alfred-vars.yml'
    dest='/etc/alfred/alfred-vars.yml'

- name: body is gathered
  become_user: alfred
  git:
    repo="{{ item.url }}"
    dest="/var/lib/alfred/plugins/{{ item.name }}"
    version="{{ item.version }}"
    accept_hostkey=yes
  with_items: "{{ alfred.modules }}"

- name: User is sudoer
  lineinfile: "dest=/etc/sudoers state='present' regexp='^alfred' line='alfred ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s' "

# add source user to group alfred

- name: every plugin is installed
  become_user: alfred
  shell: "ansible-playbook /var/lib/alfred/playbooks/install-alfred-plugin.yml -e 'plugin_name={{ item.name }}'"
  with_items: "{{ alfred.modules }}"
