---
- name: system is up-to-date
  apt:
    update_cache=yes
    upgrade=full

- name: blocking packages are absent
  apt:
    pkg=python-pip
    state=absent
    purge=yes

- name: toolbox is well equipped
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - git
    - aptitude
    - python-setuptools
    - python-dev
    - libffi-dev
    - libssl-dev
    - libzmq3-dev
    - libzmq3

- name: pip is installed
  easy_install:
    name=pip

- name: mandatory python packages are installed
  pip:
    name="{{ item }}"
    state=latest
  with_items:
    - pip
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    - ansible
    - pyzmq
    - virtualenv

- name: ansible configuration directory is ready
  file:
    path='/etc/ansible'
    state='directory'
    owner='root'
    group='root'
    mode='0755'

- name: default host inventory is present
  template:
    src='alfred_hosts.j2'
    dest='/etc/ansible/hosts'
    owner='root'
    group='root'
    mode='0644'

- name: alfred is a system user
  user:
    name=alfred
    home="{{ alfred.home }}"
    generate_ssh_key=yes
    system=yes
    ssh_key_bits=4096
    state=present

- name: default env variables are in place
  template:
    src='etc_default.j2'
    dest='/etc/default/alfred'
    owner='root'
    group='root'
    mode='0644'
  notify: restart alfred

- name: plugins dirs ready
  become_user: alfred
  file:
    path="{{ alfred.home }}/{{ item }}"
    state=directory
  with_items:
    - plugins
    - virtualenv

- name: run ipc directory is ready
  file:
    path="/var/run/alfred"
    state=directory
    owner=alfred
    group=alfred
    mode=2750

- name: utils playbooks directory ready
  file:
    path=/etc/ansible/playbooks
    state=directory

- name: alfred action playbooks are present
  copy:
    src=install-plugin.yml
    dest=/etc/ansible/playbooks/install-alfred-plugin.yml

- name: alfred variables are present
  copy:
    src='alfred-vars.yml'
    dest='/etc/ansible/alfred-vars.yml'

- name: body is gathered
  git:
    repo="{{ item.url }}"
    dest="{{ alfred.home }}/plugins/{{ item.name }}"
    version="{{ item.version }}"
    accept_hostkey=yes
  with_items: "{{ alfred.modules }}"

- name: every plugin is installed
  shell: "ansible-playbook /etc/ansible/playbooks/install-alfred-plugin.yml -e 'plugin_name={{ item.name }}'"
  with_items: "{{ alfred.modules }}"
