---
- hosts: local
  become: yes
  become_user: alfred

  vars_files:
    - '/etc/ansible/alfred-vars.yml'

  tasks:
    - name: prepared virtualenv
      shell: "virtualenv {{ alfred.home }}/virtualenv/{{ plugin_name }}"
      args:
        creates: "{{ alfred.home }}/virtualenv/{{ plugin_name }}"

    - name: install pip dependencies
      pip:
        name="{{ item }}"
        virtualenv="{{ alfred.home }}/virtualenv/{{ plugin_name }}"
        state=latest
      with_items: "{{ alfred_plugin.pip_packages }}"
